services:
  gtm-control:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gtm-control
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - n8n_network

  gtm-action-web:
    image: ghcr.io/mlupu88/druid-gtm-control/gtm-action-web:latest
    restart: unless-stopped
    networks:
      - n8n_network

networks:
  n8n_network:
    external: true
