// shared/mockData.js — mock ICP_Review_Queue rows matching the real schema exactly.
// Used as fallback when Google Sheets creds are absent, so the UI works before wiring.
export const MOCK_QUEUE = [
  { queue_key:"j.rivera@acme-insure.com", queue_id:"j.rivera@acme-insure.com", signal_at:"2026-06-30T08:12:00Z",
    company_domain:"acme-insure.com", company_name:"Acme Insurance", country:"US", stream:"us",
    resolution_level:"person", industry:"Insurance", vertical:"FinServ", account_score:"118", score_tier:"outbound_now",
    contact_name:"Jordan Rivera", contact_email:"j.rivera@acme-insure.com", contact_phone:"+14155550142",
    recommended_solution:"Customer Self-Service & Claims Automation", why_now:"US person-level visitor match (RB2B) on /solutions/claims; active search intent",
    recommended_action:"Approve AI buyer-qualification call (Retell)", tool:"Retell", consumes_credits:"yes",
    cost_impact:"medium", cost_explanation:"If approved, n8n may launch a Retell call. US voice requires TCPA clearance.",
    gate_status:"blocked", block_reason:"us_voice_not_cleared",
    gate_detail:JSON.stringify({internal_exclusion:"passed",suppression:"passed",do_not_contact:"passed",phone_valid:"passed",us_voice_cleared:"failed"}),
    engine_status:"pending_review", last_signal_source:"rb2b", engine_mode:"live", test_mode:"false",
    operator_decision:"", approved_by:"", approved_at:"", reason:"", final_status:"", processed_at:"" },

  { queue_key:"stadtklinik.de", queue_id:"stadtklinik.de", signal_at:"2026-06-30T07:50:00Z",
    company_domain:"stadtklinik.de", company_name:"StadtKlinik Group", country:"DE", stream:"emea",
    resolution_level:"company", industry:"Healthcare", vertical:"Healthcare", account_score:"86", score_tier:"sales_review",
    contact_name:"", contact_email:"", contact_phone:"",
    recommended_solution:"Patient Scheduling & Intake Automation",
    why_now:"EMEA company-level visit detected (Dealfront) + committee reconstructed (Cognism)",
    recommended_action:"Approve LinkedIn outreach (Dripify)", tool:"Dripify", consumes_credits:"maybe",
    cost_impact:"low", cost_explanation:"May consume seat/action limits; affects LinkedIn account safety.",
    gate_status:"passed", block_reason:"",
    gate_detail:JSON.stringify({internal_exclusion:"passed",suppression:"passed",do_not_contact:"passed",linkedin_available:"passed"}),
    engine_status:"pending_review", last_signal_source:"dealfront", engine_mode:"live", test_mode:"false",
    operator_decision:"", approved_by:"", approved_at:"", reason:"", final_status:"", processed_at:"" },

  { queue_key:"druidai.com", queue_id:"druidai.com", signal_at:"2026-06-30T09:01:00Z",
    company_domain:"druidai.com", company_name:"DRUID AI", country:"RO", stream:"emea",
    resolution_level:"person", industry:"Software", vertical:"Technology", account_score:"0", score_tier:"nurture",
    contact_name:"Internal User", contact_email:"someone@druidai.com", contact_phone:"",
    recommended_solution:"", why_now:"Internal/test activity",
    recommended_action:"Suppressed - no action", tool:"-", consumes_credits:"no", cost_impact:"none",
    cost_explanation:"Blocks future activation.", gate_status:"failed", block_reason:"excluded:internal",
    gate_detail:JSON.stringify({internal_exclusion:"failed",suppression:"passed",do_not_contact:"passed"}),
    engine_status:"suppressed", last_signal_source:"posthog", engine_mode:"live", test_mode:"false",
    operator_decision:"", approved_by:"", approved_at:"", reason:"", final_status:"", processed_at:"" },

  { queue_key:"m.chen@globex.com", queue_id:"m.chen@globex.com", signal_at:"2026-06-30T06:30:00Z",
    company_domain:"globex.com", company_name:"Globex Corp", country:"US", stream:"us",
    resolution_level:"person", industry:"Banking", vertical:"FinServ", account_score:"92", score_tier:"sales_review",
    contact_name:"Morgan Chen", contact_email:"m.chen@globex.com", contact_phone:"",
    recommended_solution:"Customer Self-Service & Claims Automation",
    why_now:"Known CRM/contact activity (HubSpot): pricing page revisit",
    recommended_action:"Send owner alert (HubSpot)", tool:"HubSpot", consumes_credits:"no", cost_impact:"none",
    cost_explanation:"Creates an internal task/alert only; automation stands down.",
    gate_status:"passed", block_reason:"",
    gate_detail:JSON.stringify({internal_exclusion:"passed",suppression:"passed",do_not_contact:"passed",known_owner:"warning"}),
    engine_status:"pending_review", last_signal_source:"hubspot", engine_mode:"live", test_mode:"false",
    operator_decision:"", approved_by:"", approved_at:"", reason:"", final_status:"", processed_at:"" },

  { queue_key:"test@example.com", queue_id:"test@example.com", signal_at:"2026-06-30T10:00:00Z",
    company_domain:"example.com", company_name:"Test Co", country:"US", stream:"us",
    resolution_level:"person", industry:"Software", vertical:"Technology", account_score:"105", score_tier:"outbound_now",
    contact_name:"Test Buyer", contact_email:"test@example.com", contact_phone:"+15555550000",
    recommended_solution:"Order Management & Customer Service Automation",
    why_now:"TEST SIGNAL — synthetic enrichment, no credits spent",
    recommended_action:"Approve email sequence (Salesforge)", tool:"Salesforge", consumes_credits:"maybe", cost_impact:"low",
    cost_explanation:"May consume sequence/send capacity; affects domain reputation.",
    gate_status:"passed", block_reason:"",
    gate_detail:JSON.stringify({internal_exclusion:"passed",suppression:"passed",do_not_contact:"passed",email_valid:"passed"}),
    engine_status:"pending_review", last_signal_source:"test", engine_mode:"live", test_mode:"true",
    operator_decision:"", approved_by:"", approved_at:"", reason:"", final_status:"", processed_at:"" }
];

// PHASE C: account-queue mock rows (one per output type; used when queue_source=account_queue and no sheet creds).
export const MOCK_ACCOUNT_QUEUE = [
  { account_key:"dom:globex.com", company_name:"Globex", company_domain:"globex.com", region:"us", identity_resolution:"identified_contact", match_confidence:"high", visitor_claim_allowed:"true", recommended_output:"MQL", recommended_action:"Approve email sequence", recommended_tool:"Salesforge", total_score:109, score_tier:"outbound_now", fit_score:30, interest_score:42, identity_score:16, actionability_score:6, timing_score:15, risk_score:0, why_now:"Globex engaged with /pricing (2 sources); no CRM record.", mql_reason:"MQL: fit+interest+identity+actionable, no conflict", sales_review_reason:"", best_contact_name:"Morgan Chen", best_contact_email:"m@globex.com", contact_origin:"rb2b", committee_count:1, committee_summary:"Morgan Chen [identified_contact]", gate_status:"passed", block_reason:"", engine_mode:"live", us_voice_lock:"true", hubspot_owner:"", open_opportunity:"false", existing_customer:"false", partner_flag:"false", competitor_flag:"false", operator_decision:"", final_status:"", fallback_signal_queue_present:"true", test_mode:"false" },
  { account_key:"dom:acme-insure.com", company_name:"Acme Insurance", company_domain:"acme-insure.com", region:"emea", identity_resolution:"reconstructed_contact", match_confidence:"high", visitor_claim_allowed:"false", recommended_output:"Sales Review", recommended_action:"Human review — strong account, no lawful channel yet", total_score:134, score_tier:"outbound_now", fit_score:40, interest_score:69, identity_score:10, actionability_score:0, timing_score:15, risk_score:0, why_now:"Acme Insurance appears to be exploring /insurance-claims-automation (4 sources); no CRM record.", sales_review_reason:"no_lawful_channel", best_contact_name:"Jordan Rivera", best_contact_email:"j.rivera@acme-insure.com", contact_origin:"cognism_reconstructed", committee_count:1, committee_summary:"Director of CX [reconstructed_contact]", gate_status:"warning", block_reason:"no_safe_channel", engine_mode:"live", us_voice_lock:"false", hubspot_owner:"", open_opportunity:"false", existing_customer:"false", fallback_signal_queue_present:"true", test_mode:"false" },
  { account_key:"dom:allianz-x.com", company_name:"Allianz X", region:"emea", identity_resolution:"known_crm_contact", recommended_output:"Pipeline Assist", recommended_action:"Notify opportunity owner", pipeline_assist_flag:"true", total_score:54, hubspot_owner:"Andrei", open_opportunity:"true", open_opportunity_id:"OPP7", visitor_claim_allowed:"true", why_now:"Allianz X — open opportunity exists.", fallback_signal_queue_present:"true", test_mode:"false" },
  { account_key:"dom:bigbank.com", company_name:"BigBank", region:"us", identity_resolution:"known_crm_contact", recommended_output:"Owner Alert", recommended_action:"Notify owner of new activity", owner_review_required:"true", owner_can_promote_to_mql:"true", hubspot_owner:"Andrei", total_score:59, visitor_claim_allowed:"true", why_now:"BigBank — owned by Andrei, no open opp.", fallback_signal_queue_present:"false", test_mode:"false" },
  { account_key:"dom:partner-si.com", company_name:"Partner SI", region:"emea", recommended_output:"Owner Alert", recommended_action:"Route to partner manager", partner_flag:"true", total_score:40, why_now:"Partner account — route to partner manager.", test_mode:"false" },
  { account_key:"name:some company", company_name:"Some Company Ltd", region:"emea", identity_resolution:"company_level", match_confidence:"low", recommended_output:"Sales Review", sales_review_reason:"low_confidence_match", visitor_claim_allowed:"false", total_score:56, why_now:"Some Company Ltd appears to be exploring /solutions.", test_mode:"false" },
  { account_key:"dom:donotcall.com", company_name:"DoNotCall", region:"us", recommended_output:"Suppressed", block_reason:"do_not_contact", gate_status:"failed", total_score:0, why_now:"", test_mode:"false" },
];
