// scenarioFixtures.js — the 8 approved business-validation scenarios (product decision,
// 2026-07-24), as executable test-only synthetic fixtures. These are NOT the same objects
// as MOCK_ACCOUNT_QUEUE (which remains the UI-visible Sample-mode data, unchanged by this
// file) — they exist solely to be asserted against in scenarios.test.js. Every fixture
// carries provenance:"synthetic_demo_fixture" and must never be rendered as if it were a
// real Client Radar result, real customer, or real evidence.
//
// All fixtures use the account_queue row shape (identity_resolution, fit/interest/etc.
// score fields, hubspot_owner, open_opportunity, existing_customer) since that schema alone
// carries every field the 8 scenarios need to exercise.

export const SCENARIO_FIXTURES = [
  {
    scenario_id: 1,
    scenario_name: "specific_use_case_identified_person",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:usecase-identified.example",
      company_name: "Fixture Use-Case Co",
      company_domain: "usecase-identified.example",
      region: "us",
      identity_resolution: "identified_contact",
      best_contact_name: "Fixture Contact One",
      best_contact_email: "contact-one@usecase-identified.example",
      recommended_output: "MQL",
      recommended_solution: "Customer Self-Service Automation",
      why_now: "Fixture Use-Case Co engaged with /customer-self-service-automation (3 sources); no CRM record.",
      total_score: 120, fit_score: 35, interest_score: 45, identity_score: 20, actionability_score: 10, timing_score: 10, risk_score: 0,
      visitor_claim_allowed: "true",
      consent_email: "true",
      gate_status: "passed", block_reason: "",
      engine_mode: "live",
      hubspot_owner: "", open_opportunity: "false", existing_customer: "false",
      test_mode: "false",
    },
  },
  {
    scenario_id: 2,
    scenario_name: "generic_pricing_intent",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:generic-pricing.example",
      company_name: "Fixture Pricing Co",
      company_domain: "generic-pricing.example",
      region: "us",
      identity_resolution: "identified_contact",
      best_contact_name: "Fixture Contact Two",
      recommended_output: "Sales Review",
      sales_review_reason: "below_mql_threshold",
      why_now: "Fixture Pricing Co engaged with /pricing (1 source); no CRM record.",
      total_score: 48, fit_score: 20, interest_score: 15, identity_score: 8, actionability_score: 5, timing_score: 0, risk_score: 0,
      visitor_claim_allowed: "false",
      gate_status: "passed", block_reason: "",
      engine_mode: "live",
      hubspot_owner: "", open_opportunity: "false", existing_customer: "false",
      test_mode: "false",
    },
  },
  {
    scenario_id: 3,
    scenario_name: "company_only_no_identified_person",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:company-only.example",
      company_name: "Fixture Company Only Ltd",
      company_domain: "company-only.example",
      region: "emea",
      // Deliberately paired with recommended_output:"MQL" — this proves the cockpit's own
      // identity gate blocks prospect-facing drafts even if the external engine assigns
      // MQL to a company-only signal (see product decision, 2026-07-24).
      identity_resolution: "company_level",
      recommended_output: "MQL",
      recommended_solution: "Order Management Automation",
      why_now: "Fixture Company Only Ltd appears to be exploring /order-management-automation.",
      total_score: 80, fit_score: 30, interest_score: 30, identity_score: 5, actionability_score: 10, timing_score: 5, risk_score: 0,
      visitor_claim_allowed: "false",
      gate_status: "passed", block_reason: "",
      engine_mode: "live",
      hubspot_owner: "", open_opportunity: "false", existing_customer: "false",
      test_mode: "false",
    },
  },
  {
    scenario_id: 4,
    scenario_name: "existing_open_opportunity",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:open-opportunity.example",
      company_name: "Fixture Opportunity Corp",
      company_domain: "open-opportunity.example",
      region: "emea",
      identity_resolution: "known_crm_contact",
      recommended_output: "Pipeline Assist",
      pipeline_assist_flag: "true",
      hubspot_owner: "Fixture Owner",
      open_opportunity: "true",
      open_opportunity_id: "FIXTURE-OPP-1",
      existing_customer: "false",
      why_now: "Fixture Opportunity Corp — open opportunity exists.",
      total_score: 55,
      visitor_claim_allowed: "true",
      engine_mode: "live",
      test_mode: "false",
    },
  },
  {
    scenario_id: 5,
    scenario_name: "known_owner_no_open_opportunity",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:known-owner.example",
      company_name: "Fixture Owned Co",
      company_domain: "known-owner.example",
      region: "us",
      identity_resolution: "known_crm_contact",
      recommended_output: "Owner Alert",
      owner_review_required: "true",
      owner_can_promote_to_mql: "true",
      hubspot_owner: "Fixture Owner",
      open_opportunity: "false",
      existing_customer: "false",
      why_now: "Fixture Owned Co — owned by Fixture Owner, no open opp.",
      total_score: 58,
      visitor_claim_allowed: "true",
      engine_mode: "live",
      test_mode: "false",
    },
  },
  {
    scenario_id: 6,
    scenario_name: "weak_generic_signal",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:weak-signal.example",
      company_name: "Fixture Weak Signal Inc",
      company_domain: "weak-signal.example",
      region: "us",
      identity_resolution: "anonymous",
      recommended_output: "Nurture",
      why_now: "Fixture Weak Signal Inc — single low-signal event.",
      total_score: 12, fit_score: 5, interest_score: 4, identity_score: 0, actionability_score: 0, timing_score: 3, risk_score: 0,
      hubspot_owner: "", open_opportunity: "false", existing_customer: "false",
      engine_mode: "live",
      test_mode: "false",
    },
  },
  {
    scenario_id: 7,
    scenario_name: "existing_customer_suppressed",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:suppressed.example",
      company_name: "Fixture Suppressed Co",
      company_domain: "suppressed.example",
      region: "us",
      identity_resolution: "known_crm_contact",
      recommended_output: "Suppressed",
      existing_customer: "true",
      block_reason: "suppressed_or_dnc",
      gate_status: "failed",
      hubspot_owner: "Fixture Owner",
      open_opportunity: "false",
      why_now: "",
      total_score: 0,
      engine_mode: "live",
      test_mode: "false",
    },
  },
  {
    scenario_id: 8,
    scenario_name: "identified_contact_email_basis_unknown",
    row: {
      provenance: "synthetic_demo_fixture",
      account_key: "fixture:email-basis-unknown.example",
      company_name: "Fixture Basis Unknown GmbH",
      company_domain: "email-basis-unknown.example",
      region: "emea",
      identity_resolution: "identified_contact",
      best_contact_name: "Fixture EU Contact",
      recommended_output: "MQL",
      recommended_solution: "Order Management Automation",
      why_now: "Fixture Basis Unknown GmbH engaged with /order-management-automation (2 sources); no CRM record.",
      total_score: 95, fit_score: 30, interest_score: 35, identity_score: 15, actionability_score: 10, timing_score: 5, risk_score: 0,
      consent_email: "false",
      li_basis_cleared: "false",
      visitor_claim_allowed: "true",
      gate_status: "warning", block_reason: "no_safe_channel",
      engine_mode: "live",
      hubspot_owner: "", open_opportunity: "false", existing_customer: "false",
      test_mode: "false",
    },
  },
];

export function scenarioFixture(scenarioId) {
  const found = SCENARIO_FIXTURES.find((s) => s.scenario_id === scenarioId);
  if (!found) throw new Error(`No scenario fixture with scenario_id ${scenarioId}`);
  return found.row;
}
